- DESCRIPTION
- NEWS
- R/plotly-package.r
- R/plotly.R
- tests/testthat/test-plotly-filename.R
This PR addresses issue #26.
What's posted is actually fine (resulting tree in plotly account is what you expect online).
Value `kwargs$filename` is preserved under `toJSON()` but then under `postForm()` some parsing issue generates the double directory prepending...  Which in turns propagates to `fromJSON()` -- I'm talking about https://github.com/ropensci/plotly/blob/master/R/plotly.R#L107
That's why I suggest overwriting `resp$filename` with the initial `kwargs$filename` so the returned response is what you expect -- no impact on what's actually sent to plotly (as the web platform).
Note that the resulting plotly plot is private by default -- is this what we expect?
/cc @sckott @chriddyp
> Fix response filepath when contains directory

- DESCRIPTION
- NEWS
- R/plotly-package.r
- R/plotly.R
- R/trace_generation.R
Sorry, the branch name has become unrelated to the PR.
`inherits()` checks the class.  It's pretty frustrating that I cannot just do
```r
is.null(class(myObject))
```
!! Class is returned as a string, so it's `"NULL"`, not `NULL`. Line 52, I'm basically checking for the existence of dimension `x.name` or `y.name`. (Don't be confused, the period does not mean anything here!)
The whitespaces are just for styling.
Thanks! @theengineear
> Support as.Date() conversion within ggplot code

- DESCRIPTION
- NEWS
- R/colour_conversion.R
- R/ggplotly.R
- R/plotly-package.r
- R/plotly.R
- R/trace_generation.R
- tests/testthat/test-ggplot-area.R
Small PR addressing issue #162 -- will update version number after review.
/cc @tdhock please :)
> Support alpha transparency in geom_area

- R/ggplotly.R
- R/trace_generation.R
- tests/testthat/test-ggplot-abline.R
- tests/testthat/test-ggplot-bar.R
- tests/testthat/test-ggplot-legend.R
- tests/testthat/test-ggplot-polygons.R
- tests/testthat/test-ggplot-size.R
- tests/testthat/test-ggplot-theme.R
- tests/testthat/test-ggplot-ylim.R
This fixes "legend doesn't hide" from #161
> Toby legend hiding

- R/ggplotly.R
- tests/testthat/test-cookbook-axes.R
This branch translates some of Marianne's visual tests from the axes.R file in the add-r-cookbook-tests branch 
https://github.com/ropensci/plotly/blob/add-r-cookbook-tests/tests/cookbook-test-suite/axes.R
to the format I need for adding them to the test table.
> Toby cookbook-axes

- DESCRIPTION
- NEWS
- R/ggplotly.R
- R/trace_generation.R
- tests/testthat/test-ggplot-ribbon.R
- tests/testthat/test-ggplot-smooth.R
This pull request re-implements ribbon as a basic polygon (in a similar fashion to [rect](https://github.com/ropensci/plotly/pull/178)).
One major benefit of doing so is that `geom_ribbon()` (and consequently `geom_smooth()`)  will respect fill/colour/group aesthetics.
> Carson ribbon

- DESCRIPTION
- NEWS
- R/ggplotly.R
- R/trace_generation.R
- tests/testthat.R
- tests/testthat/test-ggplot-bar.R
- tests/testthat/test-ggplot-histogram.R
This pull request started out as a fix for #198, but I quickly realized the implementation of `geom_bar()`/`geom_histogram()` was suboptimal for a couple reasons 
1. The binning for histograms was done by plotly. Not only is this default binning different, but that also means a number of [arguments in stat_bin](http://docs.ggplot2.org/current/stat_bin.html) are ignored. If the goal is to have a correct mapping from ggplot2 to plotly, we should let ggplot2 handle the binning, then use a type="bar" and bargap=0.
2. [This thinking](https://github.com/ropensci/plotly/blob/a9daa28a2069cf437059e642c227b082fa882f66/R/trace_generation.R#L47-L54) lead to false warnings. For example, `ggplot(mtcars, aes(factor(vs)))+geom_bar()` would throw a warning, but it shouldn’t.
> Let ggplot handle histogran binning. Fix #198

- DESCRIPTION
- NEWS
- R/trace_generation.R
- tests/testthat/test-ggplot-density.R
> geom_density() as filled area chart

- DESCRIPTION
- NEWS
- R/plotly-package.r
- R/plotly.R
- man/plotly-package.Rd
Follow @cpsievert 's suggestion to respect semantic versioning (should be part of https://github.com/ropensci/plotly/pull/210).
/cc @chriddyp @cldougl @13bzhang
> Bump version to 0.6 since change was backwards incompatible

- R/print.R
otherwise plotly will detect that the graph is in an iframe, and redirect to `.embed` anyway. so, this should make plotly embeds load ~2 seconds faster :)
cc @cpsievert
> add .embed to iframe

- R/offline.R
hey @cpsievert - minor change here. using more standard filenames for the plotly.js bundles (and http://purchasing.plot.ly/plotly-offline-r reflects this)
> update offline filenames

- R/print.R
and anyways, let the user see the appropriate http status response by visiting the web page and seeing the server's response
fixes #251 
cc @cpsievert @mkcor
> remove `url_ok` check since it won't work with proxy logins

- R/plotly.R
- R/plotly_POST.R
- inst/build-push-comment.R
> Sanitize kwargs from class "environment" before posting - Fixes #254

- DESCRIPTION
- NEWS
- R/subplots.R
- tests/testthat/test-plotly-subplot.R
Fixes a bug likely introduced by d4e214322481c89ddc857f8ba2f3fb24e65143c5.
The test shows where the bug is relevant
> subplot() bugfix

- R/offline.R
- R/print.R
file.info returns file size in bytes
`useBytes` - logical: For readChar, should nchars be regarded as a
number of bytes not characters in a multi-byte locale?
This *may* fix an issue
```
In readChar(off, file.info(off)$size) :
can only read in bytes in a non-UTF-8 MBCS locale
```
from a user with a Japanese environment
> maybe fix japanese file read error

- DESCRIPTION
- NEWS
- R/plotly.R
hey @cpsievert  -- looks like the refactor in https://github.com/ropensci/plotly/commit/0b2eeb9692a2dfd69a596252e3b4a1f82db973c6 missed a couple things with the filename kwarg. since that commit, specifying the same filename doesn't overwrite the graph:
```
> d <- diamonds[sample(nrow(diamonds), 1000), ]
> p <- plot_ly(d, x = carat, y = price, text = paste("Clarity: ", clarity), filename="test")
> p
Success! Created a new plotly here -> https://plot.ly/~christopherp/1310
> p <- plot_ly(d, x = carat, y = price, text = paste("Clarity: ", clarity), filename="test")
> p
Success! Created a new plotly here -> https://plot.ly/~christopherp/1312
```
here's a fix.
cc @cldougl
> fix filename, fileopt arguments

- DESCRIPTION
- NEWS
- inst/htmlwidgets/lib/plotlyjs/plotly-htmlwidgets.css
- inst/htmlwidgets/plotly.yaml
This pull represents the most minimal solution possible to #463, so tooltips will appear in `ioslides` presentations.  I tested with various examples in different contexts and did not notice any harmful regressions or side effects.  Duplicates #523 to see if credentials work correctly with tests.
> solution for #463 plotly in ioslides

- DESCRIPTION
- NEWS
- R/ggplotly.R
- tests/testthat/test-cookbook-axes.R
- tests/testthat/test-ggplot-labels.R
- tests/testthat/test-ggplot-legend.R
Closes #573 to pull from ropensci remote.  Also rebase to current master.
As reported in #510, axis titles can be positioned improperly depending on the size of the plot.  In a2aedacd0900bf6f447d72e3f174deb4d8cfbc91, axis titles were changed to annotations, so they are not duplicated and work much more similarly to `ggplot2`.  Unfortunately, `plotly` annotations are positioned based on a `[0,1]` scale with respect to the plot area.  This means the axis titles scale inversely and negatively to the plot size.  When the plot is small, the `x` axis title will be placed too high.  When the plot is large/high, the `x` axis title moves too far down sometimes out of the svg bounding box.
This pull changes to use `plotly` axis titles when the plot is not facetted.  When the plot is facetted, the …
> use Plotly axis titles if not facetted

- R/print.R
The fix for #581 by adding '.embed' to plotly_iframe breaks compatibility with Jupyter. 
The '.embed' extension is not added in all necessary places: New files are saved without the extension, and than they can't be loaded, because the iframe expects the extension. 
However fixing this would still not work with Jupyter, as Jupyter does not render files with the extension '.embed'. It only renders if the extension is html otherwise it shows the contents as text.
This commit is a possible suggestion that allows fix #581 to remain valid and saves graphs for Jupyter without '.embed' extension.
> No '.embed' extension for Jupyter embedded pages

- R/ggplotly.R
Currently ggplotly uses ` ,` to separate `facet_grid()` columns.
The PR changes that to `<br>` to make it more compatible with ggplot (every column on its own line).
It would also help with overlapping row/column long labels.
> ggplotly: separate facet columns by <br>

- inst/examples/plotlyLinkedClick/app.R
The purpose is to avoid error messages and confusion if and when someone clicks a point on the scatter plot [online.](https://plot.ly/r/shinyapp-linked-click/)
> Add `source` argument to both the source plot and `event_data` function

- NEWS.md
- R/ggplotly.R
- tests/testthat/test-ggplot-tooltip.R
This test case shows a plot with two lines where the tooltip does not contain the right text on all the points
The `group` aesthetic in `geom_line` is not properly set in the tooltip rendering mismatched "id: Sample2" tooltips on Sample1 data points and viceversa.
``` r
mydata <- data.frame(id = paste0("Sample", rep(1:2, times = 4)),
x = rep(1:4, each = 2),
y = rep(c(1, 10), times = 4),
stringsAsFactors = FALSE)
gplt <- ggplot(mydata) + geom_line(aes(x=x, y = y, group = id))
pltly <- plotly::ggplotly(gplt)
pltly
y_equal_ten <- grepl("y: 10", pltly$x$data[[1]]$text)
sample_2 <- grepl("id: Sample2", pltly$x$data[[1]]$text)
expect_that(all(y_equal_ten == sample_2))
```
The tooltip in the image should show "id: Sample2"
Checked against current master:
```
plotly        4.5.5.9000 2016-10-28 …
```
> Fix wrong tooltip when ggplotly with geom_line(group=)

- inst/htmlwidgets/plotly.js
Plotly makes one WebGL context per graph meaning that pages with multiple plotly WebGL graphs are exposed to the browser's context cap.  https://github.com/plotly/plotly.js/issues/337
So it is better to redraw the graph, rather than create a new one.
Thanks
> preventing too many active WebGL contexts

- R/highlight.R
The error message says it should be "plotly_relayout"
```
> highlight(ggplotly(p), on = "plotly_selected", off = 'plotly_unhover', persis = FALSE)
Error in match.arg(off, off_options) : 
'arg' should be one of “plotly_doubleclick”, “plotly_deselect”, “plotly_relayout”
> 
```
> What are the possible args for "off"?

- DESCRIPTION
- NEWS.md
- R/shiny.R
- inst/examples/shiny/async/app.R
Example:
```r
library(shiny)
library(ggplot2)
library(promises)
library(future)
plan(multisession)
plotlyOutput("plot1"),
plotlyOutput("plot2"),
plotlyOutput("plot3"),
plotlyOutput("plot4")
)
output$plot1 <- renderPlotly({
future({ Sys.sleep(2); cars }) %...>%
plot_ly(x = ~speed, y = ~dist, type = "scatter", mode = "markers")
})
output$plot2 <- renderPlotly({
future({ Sys.sleep(2); mtcars }) %...>%
{ ggplot(., aes(hp, mpg)) + geom_point() } %...>%
ggplotly()
})
output$plot3 <- renderPlotly({
plot_ly(iris, x = ~Sepal.Length, y = ~Sepal.Width,
type = "scatter", mode = "markers")
})
output$plot4 <- renderPlotly({
future({}) %...>%
{ req(FALSE) }
})
}
```
> Support Shiny async/promises based rendering

- R/ggplotly.R
- tests/testthat/test-ggplot-sf.R
> use hoverinfo skip instead of none for invisible ggplotly() colorbar trace, closes #1381

- inst/htmlwidgets/plotly.js
Closes #1141 
Run the following and make sure that by clicking on each cell of the heatmap, it prints the correct information (gee, it sure would be nice to have https://github.com/rstudio/shinytest/issues/193 to unit test this!)
```r
library(shiny)
fluidRow(column(6, h4("Heatmap based on data.frame()"),
plotlyOutput("plot1"),
h4("Selected point in heatmap"),
verbatimTextOutput("selected1")
), 
column(6, 
h4("Heatmap based on matrix()"),
plotlyOutput("plot2"),
h4("Selected point in heatmap"),
verbatimTextOutput("selected2")
)
)
)
server <- function(input, output) {
randomValues <- rnorm(9)
output$plot1 <- renderPlotly({
set.seed(1)
myData <- data.frame(x = rep(letters[1:3], times = 3), 
y = rep(as.character(1:3), each = 3), value = randomValues) …
```
> Heatmap z event data should derive from _z calc attribute

- inst/htmlwidgets/plotly.js
Closes #1406. 
The bug in #1406 happens because of the hidden trace that is used to render the colorbar. That trace has an opacity of 0, but `0 || 1` evaluates to 1 in JavaScript, so this client-side logic used to store the original opacity (needed for 'clearing' a crosstalk event) was incorrectly storing 1 (instead of 0), making that invisible trace visible when clearing the brush.
Install (`devtools::install_github("ropensci/plotly#1407")`) then make sure the behavior outlined in #1406 is fixed (i.e. a marker in the lower-left should not appear after click&drag over points and double-clicking to clear the highlight)
> Properly retain original opacity of 0

- inst/htmlwidgets/plotly.js
Crosstalk highlight events work by adding/deleting traces as needed. Currently, the deleting logic removes _all_ traces added after initial render. This change makes it so only the traces added by crosstalk are removed. 
In the example below you would expect that a new marker is added to the everytime a point is clicked. Instead, without this change, only a single marker is added (and moves `x` position after every click)
```r
library(htmlwidgets)
mtcars %>%
highlight_key() %>%
plot_ly(x = ~wt, y = ~mpg) %>%
add_markers() %>%
highlight("plotly_click") %>%
onRender("
function(el) {
window.nclicks = 0;
el.on('plotly_click', function(d) {
window.nclicks = window.nclicks + 1;
var trace = {
x: [window.nclicks],
y: [10],
type: 'scatter',
mode: 'markers'
}
Plotly.addTraces(el.id, …
```
> crosstalk should only delete traces that it has added itself

- R/utils.R
See #1448 
Install `remotes::install_github("ropensci/plotly#1449")`, then verify expectation in #1448
> Be more strict about stringifying text attribute, fixes #1448

- R/shiny.R
> events that don't emit any data should always have event priority, fixes #1466

- R/utils.R
- tests/testthat/test-plotly-sf.R
- tests/testthat/test-plotly-size.R
- tests/testthat/test-plotly.R
> Ensure size mapping always leads to array of appropriate length

- R/ggplotly.R
- R/layers2traces.R
Closes #1457.
This was a fun 🐛 to track down 🔍 
Typically, when `ggplotly()` translates a layer, it prefixes the class of the data with `"Geom*"`. This is what allows `geom2plotly()` to work off S3 methods. The `aes2plotly()` function also uses this class to query the Geom's default aesthetics from ggplot2's namespace. 
To translate the graticule that comes with `geom_sf()`/`coord_sf()`, I call `geom2trace.GeomPath()` in a fairly un-standard way:
https://github.com/ropensci/plotly/blob/4473d6454f01825e8f15783e670e6fffb017e123/R/ggplotly.R#L611
That ends up calling this code, and in this case, the value of `geom` is `data.frame`. 
https://github.com/ropensci/plotly/blob/4473d6454f01825e8f15783e670e6fffb017e123/R/layers2traces.R#L1003
As of …
> Fixes for ggplot2 >3.1.0

- R/utils.R
- tests/testthat/test-api.R
resolves the issue mentioned in #1197. I checked the tests before re-commenting them out to make this PR and they worked.
> dont srcify layout attributes so ticktext works when sending charts to plot.ly

- R/shiny.R
In order to render promises (that yield plotly objects), ggplot2 objects, and orchestrate event registration, `renderPlotly()` wraps user-supplied (reactive) expressions with `plotly:::prepareWidget()`
If a user-supplied expression contains a `return()` statement. It appears `plotly:::prepareWidget()` will exit early. For an example, see below in the testing notes and/or the example in #1528
Install `devtools::install_github("ropensci/plotly")`, then run the app:
```r
library(shiny)
plotlyOutput("myplot"),
verbatimTextOutput("hovered")
)
x <- faithful$eruptions
y <- faithful$waiting
output$myplot <- renderPlotly({
p <- plot_ly(x = x, y = y) %>%
add_markers()
return(p)
})
output$hovered <- renderPrint({ …
```
> Wrap user-supplied expression in evalq(), closes #1528

- inst/htmlwidgets/plotly.js
Fixes #1610. Note also that when `pt.pointNumbers` is populated, the `key` attribute is relayed properly
Install `remotes::install_github("ropensci/plotly")`, then run the app below. As you hover over points, information about the hovered point should appear in the R console.
```r
library(shiny)
plotlyOutput("distPlotTest")
)
server <- function(input, output) {
output$distPlotTest <- renderPlotly({
highlight_key(mtcars, ~carb) %>%
plot_ly(x = ~mtcars$carb, key = ~row.names(mtcars), type = "histogram") %>%
layout(barmode = "overlay") %>% 
highlight(on = "plotly_hover", off="plotly_deselect") 
})
observe({
print(event_data("plotly_hover"))
})
}
shinyApp(ui = ui, server = server)
```
> Improvements to algorithm for attaching key attribute for shiny's event data, fixes #1610

- R/shiny.R
Another attempt at #1539, which was merged before fully understanding the shinytest failure (my bad). Note that the merge commit was already reverted on master via https://github.com/ropensci/plotly/commit/285673153adc56ec0cbb8a01d0af4c46f3894b00
I had tested #1539 on some minimal apps, but it turns out it would fail on any `renderPlotly()` statement that contained a reactive read. For example:
```r
library(shiny)
selectInput("x", "X", names(diamonds)),
plotlyOutput("p")
)
output$p <- renderPlotly({
plot_ly(x = 1, y = 1, text = input$x)
})
}
```
```r
Error in .getReactiveEnvironment()$currentContext: Operation not allowed without an active reactive context. (You tried to do something that …
```
> Wrapping of user-supplied expressions in renderPlotly

- inst/htmlwidgets/plotly.js
@jcheng5 I dug deeper into the root issue behind #1553. It turns out that `Plotly.relayout()` mutates input to `Plotly.plot()` ([minimal example](https://codepen.io/cpsievert/pen/WNeOrjj)). Normally this doesn't pose a problem for resizing logic, but for that dynamic UI example, `renderValue` gets called twice for every widget (meaning `x.layout.width`, and `instance.width` is populated during the second render).
Anyway, after this discovery, I think it's safer to make a deep copy of `width`/`height`/`autosize` at the start of `renderValue` (instead of using attributes attached to the DOM element)
> Better resizing logic

- R/plotly_build.R
- tests/testthat/test-ggplot-lines.R
> Do not create structure with NULL to remove warnings

- tests/testthat/test-plotly-color.R
This PR won't be necessary until scales goes to CRAN. It just makes sure our test expectations are in line with the new behavior in scales.
TODO: will need to approve the new svg baseline(s)
> New version of scales no longer 'spans the gamut' of a qualitative color palette

- R/layers2traces.R
After https://github.com/tidyverse/ggplot2/commit/10fa0014, it's now possible for calculated aes to exist for all default_aes...27db11e278ce92bef7ec9a4c8be5ee3b3078c9e1 just removes any "calculated aes" that are also a "user-specified aes" from consideration when building the tooltip
27db11e278ce92bef7ec9a4c8be5ee3b3078c9e1 also changes the ordering in which the aes appear in the tooltip from:
* Layer aes
* Calculated aes
* Global aes
to what I think is a better default:
* Calculated aes
* Layer aes
* Global aes
Confirm that density appears once (not twice) in the tooltip when hovering on the density lines:
```r
p <- ggplot(mtcars, aes(x = mpg, fill = factor(cyl))) + 
geom_density()
ggplotly(p)
```
> Ignore calculated aesthetics that match specified aesthestics

- R/ggplotly.R
- tests/testthat/test-ggplot-col.R
As discussed in https://github.com/tidyverse/ggplot2/pull/3566#issuecomment-565085809, it's now possible for the ggplot2 labels/positions to contains missing values, and we should be able to simply ignore them.
> Remove missing values in ticktext/tickvals

- NEWS.md
- R/utils.R
- tests/testthat/test-facet-axis.R
This PR fixes a bug in `verify_attr` which closes #1720 and #1577 .
Adding the fix the reprex from #1720 is rendered like so
and the reprex from #1577 like so:
> Fix axis facets

- DESCRIPTION
- NEWS.md
- R/shiny.R
- R/utils.R
- man/plotly-shiny.Rd
- man/plotly_IMAGE.Rd
Adds the ability to access the new CSS styles reported in `getCurrentOutputInfo()` inside of a `renderPlotly()` context. For example:
```r
library(shiny)
tags$style(HTML("body {background-color: black; color: white}")),
tags$style(HTML("body a {color: orange}")),
plotlyOutput("p")
)
output$p <- renderPlotly({
info <- getCurrentOutputInfo()
plot_ly(x = 0:10, y = 0:10, color = I(info$accent())) %>%
layout(
font = list(color = info$fg()),
paper_bgcolor = info$bg(),
plot_bgcolor = info$bg(),
xaxis = list(
gridcolor = info$fg(),
zerolinecolor = info$fg()
),
yaxis = list(
gridcolor = info$fg(),
zerolinecolor = info$fg()
)
)
})
}
```
This'll provide the foundation **thematic** and `ggplotly()` need …
> Add reportTheme argument to plotlyOutput() for reporting CSS styles

- DESCRIPTION
- R/shiny.R
To be merged after https://github.com/ramnathv/htmlwidgets/pull/391.
This makes `renderPlotly` work with `shiny::bindCache` in the dev version of shiny. For example:
```R
library(shiny)
selectizeInput(
inputId = "cities", 
label = "Select a city", 
choices = unique(txhousing$city), 
selected = "Abilene",
multiple = TRUE
),
plotlyOutput(outputId = "p")
)
server <- function(input, output, ...) {
output$p <- renderPlotly({
message("Computing p: ", paste(input$cities, collapse = ", "))
Sys.sleep(2)
plot_ly(txhousing, x = ~date, y = ~median) %>%
filter(city %in% input$cities) %>%
group_by(city) %>%
add_lines()
}) %>% 
bindCache(input$cities)
}
```
> Add support for shiny::bindCache

- NEWS.md
- R/utils.R
- inst/htmlwidgets/plotly.js
> Prevent multiple selectize/dynamic color brushes from being rendered in shiny

- NEWS.md
- R/ggplotly.R
- R/layers2layout.R
- R/layers2traces.R
Closes #1951 and another issue with `aes()` mappings getting duplicated in tooltips (surfaced via unit tests)
> Fixes for ggplot2 3.3.4 

- DESCRIPTION
- NEWS.md
- R/ggplotly.R
Follow up to #1952. I missed the changes made in https://github.com/tidyverse/ggplot2/pull/4475, which introduces the following failures (this change fixes them):
```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure (test-animate-highlight.R:119:7): When key is equivalent to group, produce simple keys ──
tr$key == tr$name is not TRUE
`actual`:
`expected`: TRUE
── Failure (test-animate-highlight.R:120:7): When key is equivalent to group, produce simple keys ──
tr$`_isSimpleKey` is not TRUE
`actual` is NULL
`expected` is a logical vector (TRUE)
── Failure (test-animate-highlight.R:119:7): When key is equivalent to group, produce simple keys ──
tr$key == tr$name is not TRUE
`actual`:
`expected`: TRUE
── Failure (test-animate-highlight.R:120:7): When …
```
> Add crosstalk mapping to computed_mapping (not mapping) when present

- NEWS.md
- inst/htmlwidgets/plotly.js
This change makes it easier to implement smooth transitions when `renderPlotly()` is performing a redraw (by specifying `layout(transition = ...)`), which from my limited experimentation works reasonably well with `scatter` traces, especially if you have `xaxis.range`/`yaxis.range` fixed "globally". Here's a basic example:
```r
library(shiny)
plotlyOutput("p")
)
output$p <- renderPlotly({
invalidateLater(1000)
plot_ly() %>%
add_markers(x = rnorm(100), y = rnorm(100), alpha = 0.2) %>%
layout(
xaxis = list(range = c(-3, 3)),
yaxis = list(range = c(-3, 3)),
transition = list(
duration = 1000, 
easing = "linear"
)
)
})
}
```
Unfortunately `Plotly.react()` doesn't seem to support smooth …
> Use Plotly.react() to redraw in Shiny if layout.transition is populated

- NEWS.md
- R/ggplotly.R
- tests/testthat/test-plotly-subplot.R
> Avoid with() to better account for missing tickvals/ticktext

- NEWS.md
- R/layers2traces.R
- tests/testthat/test-ggplot-legend.R
Closes #2043
Closes https://github.com/plotly/plotly.R/issues/2007
> Respect guide(aes = 'none') when constructing legend entries

- NEWS.md
- R/highlight.R
- R/utils.R
- demo/crosstalk-highlight-intro.R
Seems plotly.js isn't (yet) able to support data-level modifications of a plot during `plotly_selecting`, but there is [there is hope](https://github.com/plotly/plotly.js/issues/2644#issuecomment-391152782) that one day it'll be a non-issue (so this PR will wait until https://github.com/plotly/plotly.js/issues/2687 is resolved)
More reading:
https://community.plot.ly/t/adding-traces-during-plotly-selecting/10679
https://github.com/plotly/plotly.js/issues/2644
https://github.com/plotly/plotly.js/issues/2687
https://github.com/plotly/plotly.js/issues/2643
> Add 'plotly_selecting' to acceptable 'on' events

- NEWS.md
- inst/htmlwidgets/plotly.js
Hi, this is my first PR to this repository and I have reviewed the contributing guidelines. However I wasn't sure if it was necessary to create an issue first, or how to write tests for this change, so I'm open to suggestions.
I was having an issue using plotly with crosstalk filtering, where if all filters were cleared, the filtering would not be removed correctly and an exception would be raised in the browser console. This PR fixes that issue.
```r
library(crosstalk)
library(DT)
data(iris)
shared_iris <- SharedData$new(iris)
a <- plot_ly(shared_iris, x = ~Sepal.Length, y = ~Sepal.Width) %>%
add_markers() %>%
highlight(on = "plotly_click", dynamic = TRUE)
b <- datatable(shared_iris)
bscols(
list(
filter_checkbox("species", "Species", shared_iris, ~Species)
),
a, b 
)
``` …
> plotly.js fix bug when crosstalk filter keys are null

- NEWS.md
- R/layers2traces.R
Hey there! This warning came up in an app I work on and I saw there was some previous discussion that yall might be open to transitioning your {tidyr} code over to the new pivoting syntax.
The transitions are all relatively similar to each other and follow this form:
``` r
library(tidyr)
library(testthat)
#> 
#> Attaching package: 'testthat'
#> The following object is masked from 'package:tidyr':
#> 
#>     matches
vt <- "x"
relig_income <- as.data.frame(relig_income)
expect_equal(
relig_income %>%
pivot_longer(cols = "religion", names_to = "income", values_to = vt) %>%
as.data.frame(),
relig_income %>%
gather_(gather_cols = "religion", key_col = "income", value_col = vt) 
)
#> Warning: `gather_()` was deprecated in tidyr 1.2.0.
#> Please use `gather()` instead.
#> This warning is …
```
> transition `tidyr::gather_` -> `tidyr::pivot_longer`

- NEWS.md
- R/helpers.R
- tests/testthat/test-plotly-subplot.R
`nativeRaster` objects allow for a much direct and faster rasterizing. If you want to know better about them and their performance I suggest to check the https://github.com/coolbutuseless/nara package (not on CRAN at least for now).
ggplot2 already supports nativeRaster objects through `annotation_raster()`, however `ggplotly` fails to render it due to a minor limitation in `raster2uri()`.
This small pull request:
- Adds support for nativeRaster objects in raster2uri
- Adds a corresponding unit test 
- Adds the entry to the news
I would really appreciate to see this merged, because right now rasterizing large images is a very slow process.
Thanks!
> Support nativeRaster objects in annotation_raster() and raster2uri()

- R/shiny.R
- inst/htmlwidgets/lib/plotlyjs/plotly-htmlwidgets.css
In anticipation of https://github.com/ramnathv/htmlwidgets/pull/437 (and https://github.com/rstudio/bslib/pull/452)
> plotlyOutput()'s width and height now default to NULL

- NEWS.md
- R/shiny.R
- inst/htmlwidgets/lib/plotlyjs/plotly-htmlwidgets.css
- man/plotly-shiny.Rd
Also reverts changes made in #2192
> Add fill argument to `plotlyOutput()`

- NEWS.md
- R/layers2traces.R
- tests/testthat/test-ggplot-area.R
> Make ribbon_dat() a no-op if there is no data

- R/kaleido.R
The code needs access to the Python sys module to run. Otherwise it gives a missing package error. The following code generates the error: 
```r
devtools::install_github("ropensci/plotly")
library(reticulate)
fig <- plot_ly(midwest, x = ~percollege, color = ~state, type = "box")
reticulate::install_miniconda()
reticulate::conda_install('r-reticulate', 'python-kaleido')
reticulate::conda_install('r-reticulate', 'plotly', channel = 'plotly')
reticulate::use_miniconda('r-reticulate')
save_image(fig,file="image.png", height=500, width=700)
```
The error is: 
```r
> save_image(fig,file="image.png", height=500, width=700)
Error in py_run_string_impl(code, local, convert) : 
NameError: name 'sys' is not defined
```
This has been solved by importing the sys package in the Python …
> Fix kaleido image export bug

- NEWS.md
- R/plotly_build.R
- R/utils.R
The RStudio on Windows with scattergl is working for me as documented in #2296.
I'd say this closes #1214.
I would appreciate if someone (@daattali ?) who had issues with webgl rstudio and windows could verify the issues are also solved for them by running this on RStudio and seeing the plot in the viewer panel:
```r
library(ggplot2)
gplt <- ggplot(iris) + geom_point(aes(x= Sepal.Length, y = Sepal.Width))
gplt |> toWebGL()
```
Thanks!
> Fix rstudio windows warning

- NEWS.md
- R/layers2traces.R
- tests/testthat/test-ggplot-point.R
I'm unable right now to paste images here. However the plot `p` below gives a red and a green dot with ggplot2 and two green dots with plotly.
```r
df <- data.frame(x = c(1,2), y = c(0,0), color = rep("yellow", 2), fill = 1:2)
p <- ggplot(df) +
geom_point(aes(x = x, y = y, fill = fill, color = color), size = 5, shape = 21) +
scale_fill_gradient(low = "green", high = "red")
ggplotly(p)
```
`ggplotly(p)` gives the following warning as well:
> Warning message:
>In L$marker$color[idx] <- aes2plotly(data, params, "fill")[idx] :
>  number of items to replace is not a multiple of replacement length
This PR addresses the warning and fixes the issue. It's fairly simple.
> Fix geom2trace.geompoint incorrect filling (closes #2298)

- NEWS.md
- R/ggplotly.R
Mirrors changes in https://github.com/tidyverse/ggplot2/pull/5483. Note that is a follow-up of sorts to #2262 and #2301 where this new guide logic first started introducing breaking changes (which hasn't yet been released to CRAN, so we won't bother with backwards-compat for the old API)
> Updates for recent changes to ggplot2 ggproto guide API

- README.md
I suggest removing this old rOpenSci footer from the package README, as it can confuse users about the current status of this package.  We're very glad to have been a home for this package in its early days and would be happy if you wanted to note that somewhere in the repo or documentation.
> Remove footer from README.md

- NEWS.md
- R/shiny.R
Closes #2337 by wrapping `names(session$userData$plotlyInputStore)` with `shiny::isolate()`.
I don't think there's any good way to write an automated test for this, but you can verify that the reprex I gave in the issue no longer produces the spurious updates, while the click data continues to be correctly displayed.
> Isolate `names(...)` in `event_data()` to prevent spurious updates

- R/ggplotly.R
- R/layers2traces.R
- tests/testthat/test-ggplot-area.R
- tests/testthat/test-ggplot-point.R
- tests/testthat/test-ggplot-quantile.R
Hi Carson and other maintainers,
Apologies for the cold PR!
While building a new feature in ggplot2 we found through reverse dependency checks that {plotly} was negatively affected by the changes we'd like to implement. The new feature makes extensive use of computed values in the `Geom$default_aes` field, contrasted by mostly fixed values in the current CRAN version. Mostly, this PR resolves the relevant defaults before using them in {plotly}. The changes herein should be backwards compatible (locally tested with ggplot2 3.5.1).
In addition, a small change with regards to label setup is sneaked in for good measure.
If you rather have a separate PR for that I'll prepare one.
We don't intend to release a new version of ggplot2 this year, so there isn't much of a hurry to merge this.
> Compatibility with incoming ggplot2 changes

- DESCRIPTION
As seen here and a few other places:
https://github.com/plotly/plotly.R/blob/44499f21d5610175d2ca65c202fbe07dac41d6f6/tests/testthat/test-ggplot-sf.R#L4
> Add implicit Suggests 's2' explicitly

- NEWS.md
- R/utils.R
Fix for #2376 and #994.
Simply adds boxmode as a valid attribute option in the attrs_name_check function of utils.R.
Warning no longer appears for boxmode option.
Tests run without error or warning.
@cpsievert @KasperSkytte
> include boxmode as valid attr

- R/plotly_build.R
`RColorBrewer::brewer.pal()` throws an (in this case) unnecessary warning if the output plot requires less than 2 colors. This is an easy fix, and does not change the workings of the code since `RColorBrewer::brewer.pal()` never returns less than three levels anywas:
```
> RColorBrewer::brewer.pal(2, "Set2")
[1] "#66C2A5" "#FC8D62" "#8DA0CB"
Warning message:
In RColorBrewer::brewer.pal(2, "Set2") :
minimal value for n is 3, returning requested palette with 3 different levels
```
> Prevent RColorBrewer::brewer.pal warning
