- .gitignore
- .push_test_table.sh
- .travis.yml
I've been unable to successfully run `make` over at plotly-test-table (see [here](https://github.com/ropensci/plotly-test-table/issues/2) &[here](https://github.com/ropensci/plotly-test-table/issues/5))
Instead of wasting more time trying to debug on different machines, I thought it would be better to automate the job with Travis (as described [here](https://github.com/ropensci/plotly-test-table/issues/4)).
Let me know what you think @tdhock @chriddyp @mkcor
> Carson travis hook

- .travis.yml
- R/plotly.R
- R/plotly_POST.R
- inst/build-push-comment.R
hey @cpsievert - this look right? In response to this stack overflow question: http://stackoverflow.com/questions/31935305/r-plotly-ggplot
> if user supplied text, don't auto-fill text attribute with size info

- R/subplots.R
> Bug fix for subplot()

- DESCRIPTION
- NEWS
- R/offline.R
see commit for details. cc @cpsievert !
> Fix markdownToHTML for offline mode

- inst/examples/Movies/server.R
movies is no longer contained within ggplot2 https://cran.r-project.org/web/packages/ggplot2movies/index.html
> modified example to load ggplot2movies

- R/plotly.R
- inst/htmlwidgets/plotly.yaml
> Test bed for dependency declaration

- README.md
> change workshop dates

- R/ggplotly.R
https://github.com/tidyverse/ggplot2
> ggplot2's new GitHub location

- README.md
https://github.com/tidyverse/ggplot2
> ggplot2's new GitHub organization

- DESCRIPTION
Hi @cpsievert!
I noticed your little ORCiD badge on https://cran.r-project.org/web/packages/plotly/index.html so I thought I would start using mine as well...
Best,
Marianne
> Add ORCID iD for display on CRAN

- R/orca.R
This checks the help page to ensure that the installed orca is plotly's orca.
Closes #1425
> Check for plotly's orca not just orca

- R/layers2traces.R
- tests/testthat/test-ggplot-hline.R
- tests/testthat/test-ggplot-vline.R
> Generation of non-intercept data in hline/vline should respect coord_flip()

- R/shiny.R
> Fix preparation for shiny rendering

- inst/htmlwidgets/plotly.js
> Call setInputValue only if it's defined, closes #1624

- R/ggplotly.R
> Respect sf's plot12 graticule attribute when building axis ticks

- R/utils.R
- tests/testthat/test-plotly.R
> verify_webgl() shouldn't warn about types that are already gl

- R/ggplotly.R
Closes #2013
To be merged after #2063
> More careful joining of group columns

- R/layers2traces.R
Follow up to #2063 (this should've been done there and should fix failing unit tests)
> Test discrete-ness of fill after statistics have been calculated

- R/subplots.R
Changed broken URL at the end of subplots description
> Fixed broken URL in subplot.R

- DESCRIPTION
With #2262 , can the remote be removed?
> Relocate tidyverse/ggplot2 remote to `Config/Needs/check`
